export const SUPABASE_URL = 'https://xlzsnjxnkhjxngcxnpmx.supabase.co'
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsenNuanhua2hqeG5nY3hucG14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0MTc1NTQsImV4cCI6MjA1MDk5MzU1NH0.eJjBsHxPczPsreaDeplMqRKzRPre7CAG5Z8_7b6Hweo'
